In [7]:
import numpy as np
a = np.array([[3,5,7], [8,9,10]])
print(a)

[[ 3  5  7]
 [ 8  9 10]]


In [3]:
a = np.array([[[10, 20, 30], [9, 15, 56]], [[51, 72, 33], [24, 65, 46]]])
print(a)

[[[10 20 30]
  [ 9 15 56]]

 [[51 72 33]
  [24 65 46]]]


In [8]:
a = np.array([1, 2, 3, 4])
print(a[1])

2


In [9]:
a = np.array([1, 2, 3, 4])
print(a[0] + a[3])

5


In [ ]:
a = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('3rd value on 2nd row: ', a[1, 2])

3rd value on 2nd row:  8


In [10]:
a = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(a[0, 1, 2])

6


In [ ]:
import pandas as ps
data = {
  "Name": ["ram", "abc", "asd"],
  "Age": [5, 7, 9]
}
#load data into a DataFrame object
dn = ps.DataFrame(data)
print(dn)

  Name  Age
0  ram    5
1  abc    7
2  asd    9


In [ ]:
print(dn.loc[0])

Name    ram
Age       5
Name: 0, dtype: object


In [ ]:
print(dn.loc[[0, 1]])
print(dn.loc[[0, 1,2]])

  Name  Age
0  ram    5
1  abc    7
  Name  Age
0  ram    5
1  abc    7
2  asd    9


In [11]:
import pandas as pd
data = {
  "Name": ["ram", "abc", "asd"],
  "Age": [5, 7, 9]
}
d = pd.DataFrame(data, index = ["User 1", "User 2", "User 3"])

print(d)

       Name  Age
User 1  ram    5
User 2  abc    7
User 3  asd    9


In [ ]:
import pandas as pd
df = pd.read_csv('/content/employees.csv')
print(df)

    First Name  Gender  Start Date Last Login Time  Salary  Bonus %  \
0      Douglas    Male    8/6/1993        12:42 PM   97308    6.945   
1       Thomas    Male   3/31/1996         6:53 AM   61933    4.170   
2        Maria  Female   4/23/1993        11:17 AM  130590   11.858   
3        Jerry    Male    3/4/2005         1:00 PM  138705    9.340   
4        Larry    Male   1/24/1998         4:47 PM  101004    1.389   
..         ...     ...         ...             ...     ...      ...   
995      Henry     NaN  11/23/2014         6:09 AM  132483   16.655   
996    Phillip    Male   1/31/1984         6:30 AM   42392   19.675   
997    Russell    Male   5/20/2013        12:39 PM   96914    1.421   
998      Larry    Male   4/20/2013         4:45 PM   60500   11.985   
999     Albert    Male   5/15/2012         6:24 PM  129949   10.169   

    Senior Management                  Team  
0                True             Marketing  
1                True                   NaN  
2        

In [ ]:
df = pd.read_csv('/content/employees.csv')
print(df.head(10))

  First Name  Gender  Start Date Last Login Time  Salary  Bonus %  \
0    Douglas    Male    8/6/1993        12:42 PM   97308    6.945   
1     Thomas    Male   3/31/1996         6:53 AM   61933    4.170   
2      Maria  Female   4/23/1993        11:17 AM  130590   11.858   
3      Jerry    Male    3/4/2005         1:00 PM  138705    9.340   
4      Larry    Male   1/24/1998         4:47 PM  101004    1.389   
5     Dennis    Male   4/18/1987         1:35 AM  115163   10.125   
6       Ruby  Female   8/17/1987         4:20 PM   65476   10.012   
7        NaN  Female   7/20/2015        10:43 AM   45906   11.598   
8     Angela  Female  11/22/2005         6:29 AM   95570   18.523   
9    Frances  Female    8/8/2002         6:51 AM  139852    7.524   

  Senior Management                  Team  
0              True             Marketing  
1              True                   NaN  
2             False               Finance  
3              True               Finance  
4              True 

In [ ]:
import pandas as pd
df = pd.read_csv('/content/employees.csv')
print(df.head())

  First Name  Gender Start Date Last Login Time  Salary  Bonus %  \
0    Douglas    Male   8/6/1993        12:42 PM   97308    6.945   
1     Thomas    Male  3/31/1996         6:53 AM   61933    4.170   
2      Maria  Female  4/23/1993        11:17 AM  130590   11.858   
3      Jerry    Male   3/4/2005         1:00 PM  138705    9.340   
4      Larry    Male  1/24/1998         4:47 PM  101004    1.389   

  Senior Management             Team  
0              True        Marketing  
1              True              NaN  
2             False          Finance  
3              True          Finance  
4              True  Client Services  


In [ ]:
import pandas as pd
df = pd.read_csv('/content/employees.csv')
print(df.tail())

    First Name Gender  Start Date Last Login Time  Salary  Bonus %  \
995      Henry    NaN  11/23/2014         6:09 AM  132483   16.655   
996    Phillip   Male   1/31/1984         6:30 AM   42392   19.675   
997    Russell   Male   5/20/2013        12:39 PM   96914    1.421   
998      Larry   Male   4/20/2013         4:45 PM   60500   11.985   
999     Albert   Male   5/15/2012         6:24 PM  129949   10.169   

    Senior Management                  Team  
995             False          Distribution  
996             False               Finance  
997             False               Product  
998             False  Business Development  
999              True                 Sales  


In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   First Name         933 non-null    object 
 1   Gender             855 non-null    object 
 2   Start Date         1000 non-null   object 
 3   Last Login Time    1000 non-null   object 
 4   Salary             1000 non-null   int64  
 5   Bonus %            1000 non-null   float64
 6   Senior Management  933 non-null    object 
 7   Team               957 non-null    object 
dtypes: float64(1), int64(1), object(6)
memory usage: 62.6+ KB
None


In [ ]:
#Handle Missing Values

In [12]:

import pandas as pd
import numpy as np
d1 = {'First value':[10, 90, np.nan, np.nan],
		'Second value': [np.nan, 4, 6, np.nan],
		'Third Score':[40, 80, np.nan, 97]}
d = pd.DataFrame(d1)
d.isnull()


First value  Second value  Third Score
0        False          True        False
1        False         False        False
2         True         False         True
3         True          True        False

from matplotlib import pyplot as plt
import seaborn as sns
_df_0.groupby('First value').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_1.groupby('Second value').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_2.groupby('Third Score').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['Second value'].value_counts()
    for x_label, grp in _df_3.groupby('First value')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('First value')
_ = plt.ylabel('Second value')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['Third Score'].value_counts()
    for x_label, grp in _df_4.groupby('Second value')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('Second value')
_ = plt.ylabel('Third Score')

In [ ]:
d.fillna(0)


First value  Second value  Third Score
0         10.0           0.0         40.0
1         90.0           4.0         80.0
2          0.0           6.0          0.0
3          0.0           0.0         97.0

In [ ]:
d.fillna(method ='pad')


First value  Second value  Third Score
0         10.0           NaN         40.0
1         90.0           4.0         80.0
2         90.0           6.0         80.0
3         90.0           6.0         97.0

In [ ]:
d.fillna(method ='bfill')

First value  Second value  Third Score
0         10.0           4.0         40.0
1         90.0           4.0         80.0
2          NaN           6.0         97.0
3          NaN           NaN         97.0

In [ ]:
data = pd.read_csv("employees.csv")
data[10:50]


First Name  Gender  Start Date Last Login Time  Salary  Bonus %  \
10     Louise  Female   8/12/1980         9:01 AM   63241   15.132   
11      Julie  Female  10/26/1997         3:19 PM  102508   12.637   
12    Brandon    Male   12/1/1980         1:08 AM  112807   17.492   
13       Gary    Male   1/27/2008        11:40 PM  109831    5.831   
14   Kimberly  Female   1/14/1999         7:13 AM   41426   14.543   
15    Lillian  Female    6/5/2016         6:09 AM   59414    1.256   
16     Jeremy    Male   9/21/2010         5:56 AM   90370    7.369   
17      Shawn    Male   12/7/1986         7:45 PM  111737    6.414   
18      Diana  Female  10/23/1981        10:27 AM  132940   19.082   
19      Donna  Female   7/22/2010         3:48 AM   81014    1.894   
20       Lois     NaN   4/22/1995         7:18 PM   64714    4.934   
21    Matthew    Male    9/5/1995         2:12 AM  100612   13.645   
22     Joshua     NaN    3/8/2012         1:58 AM   90816   18.816   
23        NaN    Male   6/14/2012         4:19 PM  125792    5.042   
24       John    Male    7/1/1992        10:08 PM   97950   13.873   
25        NaN    Male   10/8/2012         1:12 AM   37076   18.576   
26      Craig    Male   2/27/2000         7:45 AM   37598    7.757   
27      Scott     NaN   7/11/1991         6:58 PM  122367    5.218   
28      Terry    Male  11/27/1981         6:30 PM  124008   13.464   
29   Benjamin    Male   1/26/2005        10:06 PM   79529    7.008   
30  Christina  Female    8/6/2002         1:19 PM  118780    9.096   
31      Joyce     NaN   2/20/2005         2:40 PM   88657   12.752   
32        NaN    Male   8/21/1998         2:27 PM  122340    6.417   
33       Jean  Female  12/18/1993         9:07 AM  119082   16.180   
34      Jerry    Male   1/10/2004        12:56 PM   95734   19.096   
35    Theresa  Female  10/10/2006         1:12 AM   85182   16.675   
36     Rachel  Female   2/16/2009         8:47 PM  142032   12.599   
37      Linda  Female  10/19/1981         8:49 PM   57427    9.557   
38  Stephanie  Female   9/13/1986         1:52 AM   36844    5.574   
39        NaN    Male   1/29/2016         2:33 AM  122173    7.797   
40    Michael    Male  10/10/2008        11:25 AM   99283    2.665   
41  Christine     NaN   6/28/2015         1:08 AM   66582   11.308   
42    Beverly  Female    9/9/1998         8:26 PM  121918   15.835   
43    Marilyn  Female   12/7/1980         3:16 AM   73524    5.207   
44    Cynthia  Female  11/16/1988         6:54 PM  145146    7.482   
45      Roger    Male   4/17/1980        11:32 AM   88010   13.886   
46      Bruce    Male  11/28/2009        10:47 PM  114796    6.796   
47      Kathy  Female   6/22/2005         4:51 AM   66820    9.000   
48   Clarence    Male   3/26/1996         5:57 AM   93581    6.083   
49      Chris     NaN   1/24/1980        12:13 PM  113590    3.055   

   Senior Management                  Team  
10              True                   NaN  
11              True                 Legal  
12              True       Human Resources  
13             False                 Sales  
14              True               Finance  
15             False               Product  
16             False       Human Resources  
17             False               Product  
18             False       Client Services  
19             False               Product  
20              True                 Legal  
21             False             Marketing  
22              True       Client Services  
23               NaN                   NaN  
24             False       Client Services  
25               NaN       Client Services  
26              True             Marketing  
27             False                 Legal  
28              True       Client Services  
29              True                 Legal  
30              True           Engineering  
31             False               Product  
32               NaN                   NaN  
33             False  Business Development  
34     

In [ ]:

data["Gender"].fillna("No Gender", inplace = True)
data


First Name     Gender  Start Date Last Login Time  Salary  Bonus %  \
0      Douglas       Male    8/6/1993        12:42 PM   97308    6.945   
1       Thomas       Male   3/31/1996         6:53 AM   61933    4.170   
2        Maria     Female   4/23/1993        11:17 AM  130590   11.858   
3        Jerry       Male    3/4/2005         1:00 PM  138705    9.340   
4        Larry       Male   1/24/1998         4:47 PM  101004    1.389   
..         ...        ...         ...             ...     ...      ...   
995      Henry  No Gender  11/23/2014         6:09 AM  132483   16.655   
996    Phillip       Male   1/31/1984         6:30 AM   42392   19.675   
997    Russell       Male   5/20/2013        12:39 PM   96914    1.421   
998      Larry       Male   4/20/2013         4:45 PM   60500   11.985   
999     Albert       Male   5/15/2012         6:24 PM  129949   10.169   

    Senior Management                  Team  
0                True             Marketing  
1                True                   NaN  
2               False               Finance  
3                True               Finance  
4                True       Client Services  
..                ...                   ...  
995             False          Distribution  
996             False               Finance  
997             False               Product  
998             False  Business Development  
999              True                 Sales  

[1000 rows x 8 columns]